import "../blocks/reviews/reviews.js";
import "../blocks/gallery/gallery.js";
import "../blocks/header/header.js";
import "../blocks/banner/banner.js";
import "../blocks/rating/rating.js";
import "../blocks/modal/modal.js";
import "../blocks/video/video.js";
import "../blocks/faq/faq.js";
import "../blocks/cards/cards.js";